name: Conventional Commits

on: push

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Detect push
        run: |
          echo "🔎 Push in ${{ github.base_ref }} detected."
      - uses: webiny/action-conventional-commits@v1.3.0